name: Beta
on:
    push:
        branches:
            - dev
        tags:
            - 'v*-beta.*'
jobs:
    release:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-release-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-release-
            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: aarch64-apple-darwin
            - name: Install front-end dependencies
              run: pnpm i
            - uses: Swatinem/rust-cache@v2
              with:
                  workspaces: src-tauri
            - name: Update version
              run: make update-version
            - uses: tauri-apps/tauri-action@dev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: 'v__VERSION__'
                  releaseBody: 'See the assets to download this version and install.'
                  releaseDraft: false
                  prerelease: true
                  args: --target universal-apple-darwin
        permissions:
            contents: write
            pull-requests: read
